name: IP Processor Pipeline

on:
  schedule:
    # 每12小时运行一次 (UTC时间)
    - cron: '0 */12 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  process-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create necessary directories
      run: |
        mkdir -p ips output
        
    - name: Run IP Processor
      env:
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
      run: |
        python scripts/ip_processor.py
        
    - name: Make shell scripts executable
      run: |
        chmod +x scripts/upload_to_cfkv.sh
        chmod +x scripts/upload_to_webdav.sh
        
    - name: Run first upload script
      env:
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
        FOLDER_PATH: "output"
      run: |
        cd scripts && ./upload_to_cfkv.sh
        
    - name: Run second upload script
      run: |
        cd scripts && ./upload_to_webdav.sh
        
    - name: Upload output files as artifact
      uses: actions/upload-artifact@v3
      with:
        name: output-files
        path: output/
        retention-days: 7