name: IP Processor Pipeline

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行

jobs:
  process-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Python dependencies
      run: |
        cd ip_processor
        pip install configparser==5.3.0 requests==2.31.0 tqdm==4.66.1 ipaddress==1.0.23
        
    - name: Make shell scripts executable
      run: |
        cd ip_processor
        chmod +x cloudflare_kv_upload.sh webdav_upload.sh
        
    - name: Create necessary directories
      run: |
        mkdir -p ip_processor/ips ip_processor/output
        
    - name: Run IP Processor
      run: |
        cd ip_processor
        python ip_processor.py
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
        
    - name: Run Cloudflare KV Upload
      run: |
        cd ip_processor
        ./cloudflare_kv_upload.sh
      env:
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
        FOLDER_PATH: output
        
    - name: Run WebDAV Upload
      run: |
        cd ip_processor
        ./webdav_upload.sh
      env:
        WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
        WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
        WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        
    - name: List generated files
      run: |
        echo "=== 项目目录结构 ==="
        find . -name "*.txt" -o -name "*.log" | sort
        echo "=== ip_processor/output 目录内容 ==="
        ls -la ip_processor/output/
        echo "=== 处理完成 ==="
        
    - name: Upload processed files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed-ips-${{ github.run_id }}
        path: |
          ip_processor/output/
          ip_processor/ip_processor.log
        retention-days: 30
        
    - name: Commit and push generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ip_processor/output/
        git add ip_processor/ip_processor.log
        git diff --staged --quiet || git commit -m "Auto-generated: Update processed IP files [skip ci]"
        git push
