name: IP Processor Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 12 * * *'  # 每天UTC时间12点运行

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
  CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
  CF_TOKEN: ${{ secrets.CF_TOKEN }}
  WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
  WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
  WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}

jobs:
  process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install configparser requests tqdm ipaddress
        
    - name: Make scripts executable
      run: |
        chmod +x cloudflare_kv_upload.sh webdav_upload.sh
        
    - name: Create necessary directories
      run: |
        mkdir -p ips output
        echo "目录结构:"
        ls -la
        
    - name: Run IP processor
      run: |
        python ip_processor.py
        
    - name: Upload to Cloudflare KV
      if: env.CF_DOMAIN != '' && env.CF_TOKEN != ''
      run: |
        ./cloudflare_kv_upload.sh
        
    - name: Upload to WebDAV
      if: env.WEBDAV_URL != '' && env.WEBDAV_USERNAME != '' && env.WEBDAV_PASSWORD != ''
      run: |
        ./webdav_upload.sh
        
    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ip-processor-results
        path: |
          output/
          ip_processor.log
        retention-days: 7
