name: IP Processing Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 12 * * *'  # 每天UTC时间12点运行

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
  CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
  CF_TOKEN: ${{ secrets.CF_TOKEN }}
  WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
  WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
  WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}

jobs:
  process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup environment
      run: |
        cd ip_processor
        pip install -r requirements.txt
        chmod +x *.sh
        mkdir -p ips output
        
    - name: Execute processing pipeline
      run: |
        cd ip_processor
        echo "=== 步骤1: 运行IP处理器 ==="
        python ip_processor.py
        
        echo "=== 步骤2: 上传到Cloudflare KV ==="
        ./cloudflare_kv_upload.sh || echo "Cloudflare KV上传失败或跳过"
        
        echo "=== 步骤3: 上传到WebDAV ==="
        ./webdav_upload.sh || echo "WebDAV上传失败或跳过"
        
    - name: Save workflow results
      uses: actions/upload-artifact@v4
      with:
        name: ip-processing-results
        path: ip_processor/output/
        retention-days: 7
