name: IP Processor and Upload Workflow

on:
  schedule:
    - cron: "0 */12 * * *"  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  process:
    runs-on: ubuntu-latest

    env:
      CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
      CF_TOKEN: ${{ secrets.CF_TOKEN }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
      WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
      WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 更新到v4版本

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install configparser requests tqdm ipaddress
        fi

    - name: Create directories
      run: |
        mkdir -p ips output

    - name: Run ip_processor.py
      run: |
        python ip_processor.py

    - name: Check output files
      run: |
        echo "=== 输出文件检查 ==="
        if [ -d "output" ]; then
          echo "output目录存在，内容如下："
          ls -la output/
          if [ -n "$(ls -A output/)" ]; then
            echo "文件数量: $(ls output/ | wc -l)"
            echo "文件示例："
            head -n 3 output/*.txt 2>/dev/null || echo "无法读取文件内容"
          else
            echo "output目录为空"
          fi
        else
          echo "错误: output目录不存在"
        fi

    - name: Run Cloudflare KV Upload Script
      if: env.CF_DOMAIN != '' && env.CF_TOKEN != ''
      run: |
        chmod +x cloudflare_kv_upload.sh
        ./cloudflare_kv_upload.sh

    - name: Run WebDAV Upload Script
      if: env.WEBDAV_URL != '' && env.WEBDAV_USERNAME != '' && env.WEBDAV_PASSWORD != ''
      run: |
        chmod +x webdav_upload.sh
        ./webdav_upload.sh

    # ===== 方法3：上传Artifact（替换原来的提交步骤） =====
    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ip-processor-results
        path: output/
        retention-days: 7
        if-no-files-found: warn
