name: IP Processor and Upload Workflow

on:
  schedule:
    - cron: "0 */12 * * *"  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ip_processor.py
      run: |
        python ip_processor.py

    - name: Run Cloudflare KV Upload Script
      run: |
        bash cloudflare_kv_upload.sh

    - name: Run WebDAV Upload Script
      run: |
        bash webdav_upload.sh
