name: IP Processor and Upload Workflow

on:
  schedule:
    - cron: "0 */12 * * *"  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CFKV_DOMAIN: ${{ secrets.CFKV_DOMAIN }}
      CFKV_TOKEN: ${{ secrets.CFKV_TOKEN }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
      WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
      WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
      WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ip_processor.py
      run: |
        python ip_processor.py

    - name: Run Cloudflare KV Upload Script
      run: |
        bash cloudflare_kv_upload.sh

    - name: Run WebDAV Upload Script
      run: |
        bash webdav_upload.sh

    - name: Commit and push output directory
      run: |
        cd output
        if [ -n "$(ls -A .)" ]; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-commit output files"
          git push
        else
          echo "Output directory is empty, nothing to commit."
        fi
