name: IP Processor and Upload

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行

env:
  PYTHON_VERSION: '3.10'

jobs:
  process-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create necessary directories
      run: |
        mkdir -p ips output
        ls -la
        
    - name: Generate config.ini from template
      run: |
        # 安装 envsubst 用于替换环境变量
        sudo apt-get update && sudo apt-get install -y gettext
        # 替换模板中的环境变量
        envsubst < config/config.ini.template > config.ini
        echo "生成的配置文件内容:"
        cat config.ini
        
    - name: Run IP processor
      run: |
        python scripts/ip_processor.py
        echo "处理完成，输出目录内容:"
        ls -la output/
        
    - name: Upload to Cloudflare KV (条件性)
      if: success() && env.CF_DOMAIN != '' && env.CF_TOKEN != ''
      run: |
        chmod +x scripts/cloudflare_kv_upload.sh
        scripts/cloudflare_kv_upload.sh
        
    - name: Upload to WebDAV (条件性)
      if: success() && env.WEBDAV_URL != '' && env.WEBDAV_USERNAME != '' && env.WEBDAV_PASSWORD != ''
      run: |
        chmod +x scripts/webdav_upload.sh
        scripts/webdav_upload.sh
        
    - name: Upload output files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ip-output-files
        path: output/
        retention-days: 7
