name: IP Processor Pipeline

on:
  schedule:
    # 每12小时运行一次 (UTC时间)
    - cron: '0 */12 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  process-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create necessary directories
      run: |
        mkdir -p ips output
        
    - name: Run IP Processor
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
      run: |
        python scripts/ip_processor.py
        
    - name: Make shell scripts executable
      run: |
        chmod +x scripts/upload_to_cfkv.sh
        chmod +x scripts/upload_to_webdav.sh
        
    - name: Upload to Cloudflare KV
      env:
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
      run: |
        ./scripts/upload_to_cfkv.sh  # 在项目根目录运行
        
    - name: Upload to WebDAV
      env:
        WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
        WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
        WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
      run: |
        ./scripts/upload_to_webdav.sh  # 在项目根目录运行
        
    - name: Upload output files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: output-files
        path: output/
        retention-days: 7